Replaced network model page with link to CIM profile
zepben/energy-workbench-server pull request #17
Opened 2021-01-24 23:06 UTC by ryanjcoleman

Signed-off-by: ryanjcoleman <ryan.coleman@zepben.com>

2021-01-24 23:06 UTC, ryanjcoleman commented
Task linked: [SITE-76 Urgent - Remove old database doco.](https://app.clickup.com/t/6929263/SITE-76)

2021-01-24 23:31 UTC, gcarwardine commented
@ryanjcoleman it may be helpful to put a link in to the JVM SDK stating the the EWB server is built on top of an implementation contained in the SDK.

2021-01-25 00:20 UTC, var-ram commented
@ryanjcoleman Also given that we are fixing doco that shouldn't have been there, the same fix should apply to the already released version here: https://github.com/zepben/energy-workbench-server/blob/main/docs/versioned_docs/version-2.6.0/network-model.md

2021-01-25 01:04 UTC, gcarwardine requested changes

2021-01-25 01:04 UTC, gcarwardine commented on docs/docs/network-model.md
> +If the Evolve profile doesn't contain a part of CIM that you require for your use case, you can request or propose a change to the model following the instructions at: https://github.com/zepben/evolv
So I just had a look at https://github.com/zepben/evolve-data-model and we don't actually have any information there - so probably poor place to point people. Can I suggest we either drop this or change it to say to either contact Zepben or start a discussion at the Evolve github discussion: https://github.com/zepben/evolve/discussions

2021-01-25 03:05 UTC, ryanjcoleman commented on docs/docs/network-model.md
> +If the Evolve profile doesn't contain a part of CIM that you require for your use case, you can request or propose a change to the model following the instructions at: https://github.com/zepben/evolv
Sounds good, I copied the paragraph from the SDK documentation so I'll change it there too

2021-01-25 03:16 UTC, gcarwardine approved these changes

2021-01-25 03:27 UTC, var-ram approved these changes

2021-01-25 03:27 UTC, merged